### ISSUE TITLE
Increasing the patch number instead of shadowupdates

### ISSUE THREAD

**Issue by Slluxx** [Atmosphere-NX/Atmosphere#1351]
Well, this template is pretty much useless for my request question.

I would like to request that shadow updates stop and instead a new release with increased patch or hotfix number will be made.
If thats not possible or if you have another reasons why shadow updates are a thing, id like to know them.

Thank you for your work!

**Comment by SciresM** [comment]
I do change the build revision, and note so in the zip description.

The release build replacements are because atmosphere's version is kind of a semantic API version, and as we're not yet at 1.0.0, minor is treated like major and micro is treated like minor, and we don't have a micro field.

When we're at 1.0.0, shadowfixes would simply be a micro revision bump/new release.

Wait for that, I guess?
