### ISSUE TITLE
Can't enter most homebrew apps after 0.19.1 install

### ISSUE THREAD

**Issue by dagreatbuzzsaw** [Atmosphere-NX/Atmosphere#1450]
### What's the issue you encountered?

The switch crashes upon entering homebrew apps like FTPD or Retroarch (EdiZon, oddly enough, still works). If I try to enter the apps via the menu when entering the game while holding down R, I get just a simple error message and get sent back to the Home screen. But at the menu via the Album, after entering the aformentioned apps I get error message 2144-0001 and the whole thing reboots. This all happened after I installed the latest atmosphere (0.19.1)

### How can the issue be reproduced?

Install Atmosphere 0.19.1, and try to enter FTPD, Retroarch, Checkpoint, or PPSSPP (apps I have) through either the game or the album.  Error messages differ.  Strangely EdiZon still works.

### Crash Report

https://gist.github.com/dagreatbuzzsaw/8027fcec87cce2a637d5b3150721d872

### System Firmware Version

Switch update 12.0.0

### Environment?

Fusee
Atmosphere 0.19.1
FAT32 128 GB SD card
No additional themes

### Additional context?

N/A

**Comment by SciresM** [comment]
Certain homebrew (stuff compiled with libnx < 3.0.0) needs to be re-compiled to work due to sm changes in 12.0.0 that atmosphere reimplemented in 0.19.1.

For checkpoint, I made a compatibility release: https://github.com/SciresM/Checkpoint/releases/tag/ams-19-compat

For the other stuff, make sure you're using the latest versions, and then contact the developers otherwise.
