### ISSUE TITLE
SX Mariko 12.0.0 Atmosphère 0.19.1 0xF601 (2001-0123) Error

### ISSUE THREAD

**Issue by Sorata** [Atmosphere-NX/Atmosphere#1458]
Hi friend,

SX Mariko 12.0.0
Atmosphère 0.19.1 
No game card

Launch by Hekate 5.5.5 and hekate_ipl.ini **payload=fusee-primary.bin**
When launch Atmosphère, show error: 0xF601 (2001-0123).

[fatal_reports](https://shipengliang.com/fatal_reports.zip)

Program ID:                      010000000000001f
Process Name:                    ns
Firmware:                        12.0.0 (Atmosphère 0.19.1-master-997e4dd6)

I trid goole, but no infomation helped. Such as reddit and gbatemp does not helped.

Is there any ohter suggest to solve it, or if you need more infomation, please tell me, I will add more or test about the problem.

**Comment by masagrator** [comment]
Use issue template. You have all informations that you should provide explained there.

**Comment by SciresM** [comment]
You did not use the issue templates. Re-open using them, if you must.

----

You have a partial update applied, where BOOT0 contains 11.x or lower but you have 12.x installed to system partition.

This seems to happen due to shutoff during the update process.

Restore NAND backup, and upgrade to 12.0.0 again.

Otherwise, you'll need to flash 12.0.0 BOOT0 to your console manually.

There's a decent guide for that [here](https://suchmememanyskill.github.io/guides/unbrick/).
