### ISSUE TITLE
Move config files into a common folder outside 'atmosphere'

### ISSUE THREAD

**Issue by mercur-io** [Atmosphere-NX/Atmosphere#1772]
#### Overview:
Move config files into a common folder outside 'atmosphere'

#### Smaller Details: 
In order to improve the update process, I suggest to move configuration files outside 'atmosphere' folder. That way it will be safer to remove and paste the latest version of Atmosphere without losing any of these files. Might be something like "/config/atmosphere".

#### Nature of Request:  
- Change

### What component do you feel this would best fit within?
Unknown

### Why would this feature be useful?
When updating Atmosphere, you usually have to remove the whole 'atmosphere' directory and unzip the new one. This leads to issues where people just keep removing their files inside "atmosphere/config". Having a 'config' folder outside atmosphere will simplify updating.

**Comment by masagrator** [comment]
Usually you don't need to do delete atmosphere folder. Only folder that you should delete if you have issues is "contents" inside atmosphere folder.

Otherwise it's an user fault for not updating files properly.

**Comment by SciresM** [comment]
> When updating Atmosphere, you usually have to remove the whole 'atmosphere' directory and unzip the new one

this isn't actually true, you're intended to just overwrite the ams folder.

If you always upgrade ams sequentially, this will always work.

Anyway, I like keeping stuff in atmosphere/ a lot. We already store exosphere.ini on SD root specifically so that it survives deletion of ams folder, and it's the only one that matters (since it controls blanking)/the others can just be edited as needed without deleterious or unintended effect.
