### ISSUE TITLE
Error Kernel Panic 0xf00

### ISSUE THREAD

**Issue by DarthMoor85** [Atmosphere-NX/Atmosphere#1781]
## Bug Report

A fatal error ocurred when running atmosphere.

Program ID: 524850534f53454d

Error Desc: Kernel Panic (0xf00)

![IMG_20220209_154525](https://user-images.githubusercontent.com/45493850/154338101-a91619bf-c96d-4659-9ac6-324ab541911a.jpg)

### What's the issue you encountered?

I bought the switch bricked and installed a clean sysnand 11.0.1
OFW is booting.  CFW is given error on sysnand and EmuMMC.

### How can the issue be reproduced?

After booting to Atmosphere the logo is showen
for a short moment, then black screem.

### Crash Report

[report.zip](https://github.com/Atmosphere-NX/Atmosphere/files/8082682/report.zip)

System Firmware Version
EmuMMC firmware version 11.0.1
sysNand firmware version   11.0.1

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release : 
  - [ Official release version 1.2.6  ]
- Do you have additional kips or sysmodules you're loading: ? 
- Homebrew software installed: [no ]
- EmuMMC or SysNAND: both
  - [ EmuMMC,  partition-based  ]

**Comment by SciresM** [comment]
Kernel panic due to reported-corrupted KIP...and indeed, the NCM kip header has been trashed by ARM64 code. I am not sure how this is possible, because it's happening before any decompression/etc.

Could you please message me (`SciresM#0524`) on discord so that dumps can be made of your package2 partition + constructed-package2, so that I might try to analyze this?

**Comment by DartMoor85** [comment]
I sent you a request on discord DarthMoor#8493

**Comment by SciresM** [comment]
The user's RAM is bad (stock also sees bad data reading from end of RAM, where the INI lives).
