### ISSUE TITLE
Running as a guest os on arm platform?

### ISSUE THREAD

**Issue by mio-19** [Atmosphere-NX/Atmosphere#2025]
#### Overview:
- Now that qemu-virtual board target is added, what about supporting running whole Atmosphère with GUI as a virtual machine on arm chips?

#### Smaller Details: 
- Maybe virtio-gpu-gl-pci and virtio-gpu support

### What component do you feel this would best fit within?

Kernel

### Why would this feature be useful?
[ If this is a feature for an end-user, how does it benefit the end-user? ]</br>
An alternative way to run Switch games for Apple Silicon users
[ If this feature is for developers, what does it add to Atmosphère that did not already exist? ]</br>
Debug user land components of Atmosphère more easily

**Comment by SciresM** [comment]
Atmosphere doesn't implement enormous parts of the switch OS, including all GUI code...Also, I am uninterested in using atmosphere as a means of playing games outside of official hardware, so that's kind of out of scope.

Also, it wouldn't help debugging in a way that qemu virtual doesn't -- and that target is just for kernel gdb :)
