### ISSUE TITLE
Atmosphere Hangs At Switch Logo

### ISSUE THREAD

**Issue by PixieDustDGE** [Atmosphere-NX/Atmosphere#2057]
Bug Report
What's the issue you encountered?
Atmosphere hangs at the Switch logo

How can the issue be reproduced?
Launch Atmosphere with Fusee

Crash Report
N/A

System Firmware Version
16.0.0

Environment?
Fusee, Official
SysNAND, EmuNAND File, EmuNAND Partition

Additional context?
Contents folder was deleted, replaced all necessary folders with clean versions. I've launched via TegraRcmGUI and Hekate.

**Comment by SciresM** [comment]
Okay, you made a new issue, but you *didn't answer my questions*. I also don't know why you made a new issue.

**Comment by PixieDustDGE** [comment]
It occurs on emummc both file and partition-based

**Comment by SciresM** [comment]
And does it occur on sysmmc...? Please actually test this.

**Comment by PixieDustDGE** [comment]
It does

**Comment by PixieDustDGE** [comment]
I've tried both extensively

**Comment by SciresM** [comment]
Okay. If you completely replace your emmc contents, using an unbrick guide (like https://suchmememanyskill.github.io/guides/unbrick/), does it work?

**Comment by PixieDustDGE** [comment]
I will check

**Comment by jeffyjeffy1023** [comment]
Have you tried updating Mission Control if you've installed it? That's what fixed it for me.

**Comment by SciresM** [comment]
@jeffyjeffy1023 Please do not post comments when you don't really know what you're talking about.

**Comment by kurainooni** [comment]
the easiest fix would be to just disable any system module, then try to boot.( which is the recommended step in the guide SciresM linked to, referring to Mid and Late boot errors) If you can boot to CFW, you can try to enable system modules one at a time and try to boot, to figure out which don't work right now. This helped in my case, since I could boot into stock firmware just fine, but I would get BSOD on CFW( "late boot" error).

**Comment by SciresM** [comment]
@kurainooni Please do not post comments when you don't really know what you're talking about.

The user has no custom sysmodules, per "deleted contents folder".

**Comment by urherenow** [comment]
I'd like to know how long you waited until deciding that it was frozen at the logo. Since the update, I've noticed that booting takes considerably longer than before, and the very first boot after updating emummc, it took a full couple of minutes to get to HOS. Faster after the first boot, but still longer than <16. Can you also post a screenshot of your sd info screen from nyx, please (you'll need to inject hekate for that, of course, not fusee)?

**Comment by SciresM** [comment]
@urherenow Note that that's for boots into Atmosphere 1.4.1 and higher when clearing erpt reports:

  * The mechanism for automatically cleaning up `erpt_reports` added in 1.3.0 was fixed.
    * This was actually just very fundamentally broken and has never worked, but it is verified working now.
    *  **Please note**: Your first boot into 1.4.1 may take much longer than usual (showing only a black screen), if the automatic cleanup mechanism is triggered and thousands of files are deleted. This should be one-time and not more than a minute or so, if it occurs.

That should be a one-time slowdown, since no additional logic runs on the atmosphere side except on the first boot.

**Comment by PixieDustDGE** [comment]
> Okay. If you completely replace your emmc contents, using an unbrick guide (like https://suchmememanyskill.github.io/guides/unbrick/), does it work?

It does not.

**Comment by SciresM** [comment]
...this is including on sysmmc? That is *really* surprising and shouldn't happen.

**Comment by Mr-Socket-bit** [comment]
I tried booting the switch (Sysmmc, used hekate 6.0.2), got stuck in the Switch logo screen as described here and, after waiting for a while, I got an Atmosphere crash with code 2001-0123 (0xf601). I wasn't able to replicate this on emummc partition (It just boots normally), but firmware is 15.0.1 there, while sysmmc has 16.0.0

Here's a screenshot of the full error. Hope this helps, if only a little

![image_2023-03-04_021929565](https://user-images.githubusercontent.com/84212142/222879588-c8bc1f24-3143-459e-ac88-55bfb346da75.png)

**Comment by urherenow** [comment]
Well, that tells me that your problem is different, because your problem is your sysmodules (tesla and such) are not the updated builds for fw 16.

**Comment by Waltee** [comment]
My apologies if I shouldn't be posting here, but I have over 30 consoles and 4 of them had this issue upon updating with exactly the same files as all the rest (the rest just worked perfectly). No matter how many reboots those 4 would always get stuck at the Switch logo screen. 

What fixed it for me was manually going into the atmosphere folder on the SD and manually deleting all of the crash report, error report etc. folders. 

After that every single console booted and has continued to boot flawlessly.

**Comment by urherenow** [comment]
They weren’t frozen, you were just impatient. That was a one-time deal while it was going through those reports and deleting them. But the error posted above points directly to the tesla menu. Install Tesla, built for fw 16 to take care of that.

**Comment by SciresM** [comment]
Please don't take over other people's issues.
