### ISSUE TITLE
Rename the file name switch to something else

### ISSUE THREAD

**Issue by Minecraftplayer20** [Atmosphere-NX/Atmosphere#2066]
When I was getting the latest files of Atmosphere Hekate and SD setup I was deleting the old ones from my SD and then I got thought switch was the Nintendo file and I deleted the Nintendo file and then that resulted in some of my games like youtube Fortnite and Minecraft to be deleted and Fortnite takes hours to download which I hate now I have to take hours redownloading my stuff

**Comment by Masamune3210** [comment]
One, thats not controlled by Atmosphere, that is a homebrew scene-wide thing. 
Two, that's why you shouldn't just be outright deleting things if you arent completely sure about it. Move them somewhere safe instead
Three, this is not a issue with Atmosphere and you didn't use the issue template. Please follow the issue template for actual issues and go somewhere else for things that are not issues.
