### ISSUE TITLE
there is no easy and safe fix for 1437 without a nand backup

### ISSUE THREAD

**Issue by TheKidThatCodes** [Atmosphere-NX/Atmosphere#2077]
## Feature Request

maybe add a #1437 fixer payload or tool to fix sysnands or emunands with this issue

#### Overview:
maybe add a #1437 fixer payload or tool to fix sysnands or emunands with this issue

#### Smaller Details: 
n/a

#### Nature of Request:  
- Addition

### What component do you feel this would best fit within?
idk

### Why would this feature be useful?
to make homebrew usable again for idiots like me who backup nand then blow fuses making the backup useless

**Comment by SciresM** [comment]
#1437 is a ridiculously rare issue that nobody has triggered in years.

If you're seeing 2001-0123 it's probably just because you have tesla installed and haven't updated it or something.

Also, this kind of tool isn't really in atmosphere itself's scope, someone else would be welcome to make it (and I think TegraExplorer kind of does have unbrick scripts?)
