### ISSUE TITLE
Stuck on Nintendo Splash Screen after Daybreak Update to 16.0

### ISSUE THREAD

**Issue by joeyboey** [Atmosphere-NX/Atmosphere#2102]
### What's the issue you encountered?

Today I first updated Atmosphère to the latest version (from 1.4.x to 1.5.2 which worked flawlessly).
After that I wanted to update the emummc from 15.0.1 to 16.0.
The update was downloaded via the AIO Updater and successfully installed with daybreak.
I chose the reboot option.

Now my switch is displaying the Nintendo Logo constantly. The screen dims after a few minutes, but it can be brought back by replugging the powercable. There is no other error output.
First thing was to disable all sysmodules. Nothing worked. I eventually just removed anything related to atmosphere and made a clean install.

I also tried to boot with hekate (i normally just use fusee). emummc is still present on the sd card, aswell as the corresponding config. (Is there maybe some other ini file I probably deleted?)

sysNAND boots just fine, in OFW and CFW.

I also tried to boot into maintenance mode on emummc, but the boot flag in the `system_settings.ini` did not work.

### How can the issue be reproduced?

Try to boot into emuMMC via fusee paylaod.

### Crash Report

There are no crash/error reports or logs found. The only thing is this log file `dns_mitm_startup.log`. I can share the file, but it only complaints about missing host files for the emummc.

### System Firmware Version

16.0.0</br>

### Environment?

- fusèe from atmosphere build 1.5.2
- Do you have additional kips or sysmodules you're loading:
  - initially yes, but everything worked with atmosphere (sysdvr and missioncontrol)
- EmuMMC or SysNAND:
  - Partition based RAW emummc

**Comment by joeyboey** [comment]
Is there any way to get more log output during startup? I also tried to repair the emummc with hekate. Nothing helped.

**Comment by SciresM** [comment]
How many files, if any, are inside /atmosphere/erpt_reports?

**Comment by joeyboey** [comment]
The folder is completely empty. I just made a full backup of the emummc. But it seems quite difficult to debug if there are no error messages.

**Comment by SciresM** [comment]
Yeah, there's kind of nothing to be done. To be sure, post a screenshot of /atmosphere/contents but sounds like you already removed everything in there.

All you can really do is re-clone your emummc.

There is no logging done of any kind during boot (and logging mostly cannot be done due to SD availability).

**Comment by joeyboey** [comment]
Damn thats what I expected...
Yeah I already removed the contents folder. 
Thanks for your help!
Well I try to at least get something out of the backup with [this](https://github.com/eliboa/NxNandManager).

**Comment by MysticalOS** [comment]
Had a clean working 15.0.1 switch firwmare on latest atmosphere and used daybreak to load 16.0.2 and afterwards, after nintendo logo just hard crashes. I'm thinking daybreak just kind of bricks 16.x installs atm, or at least version of it I had since I didn't think it check if THAT had an update first.

Not sure if it's same as OP but could be similarly related. my erpt_reports actually did generate all kinds of stuff though. Might gleam as to what daybreak broke here. 
[erpt_reports.zip](https://github.com/Atmosphere-NX/Atmosphere/files/11360850/erpt_reports.zip)

**Comment by Masamune3210** [comment]
Daybreak worked just fine when I updated to latest using it, and I promise you my system has been through a lot more weird experiments. Unless this is some bug that is only being triggered on emunand, I'm not sure I would solely attribute it to Daybreak

**Comment by MysticalOS** [comment]
I did some further digging and it was the Tesla overlay problem. so ignore me :D

**Comment by Masamune3210** [comment]
protip, googling a titleid can sometimes give hints as to what might be the issue. Sysmodules will almost always pick one titleid and stick to it, and some, like tesla, will actually spell out their name in the titleid to make it easier to spot.

**Comment by joeyboey** [comment]
And a last update.
Dumping my own firmware seems to have fixed the issue. But no clue on what was the problem.
