### ISSUE TITLE
Atmosphere crashes upon loading emuMMC

### ISSUE THREAD

**Issue by Rodostlyn69** [Atmosphere-NX/Atmosphere#2393]
### What's the issue you encountered?
- Atmosphere crashes when booting into the EmuMMC

### How can the issue be reproduced?
It can be reproduced by installing a theme and deleting the contents folder

### Crash Report
[01728901942_010000000000000c.log](https://github.com/user-attachments/files/17363159/01728901942_010000000000000c.log)

### System Firmware Version
- FW 18.0.1 Atmosphere 1.7.1

### Environment?
- Hekate, official release version 6.2.2 & Nyx 1.6.4
- No additional sysmodules or kips
- Homebrew App Store, NXThemes Installer, DayBreak, 90DNS Patcher
- EmuMMC partition based

Also, the contents folder in Atmosphere is missing and the folder called 010000000000000C (bcat) doesn't exist on the SD

**Comment by masagrator** [comment]
Fill the issue template that you removed.

**Comment by BaamAlex** [comment]
I comment here because I don't want to open a new issue. I have technically the same problem. I noticed that today after updating atmosphere to 1.8.0 pre-release. Firmware is on 19.0.0 on both systems. I played Zelda echoes of wisdom, paused the game, pressed the home button and let the console idle for a few minutes and before I noticed anything, my console restarted into my sysnand. And this happened twice or more today.

**Comment by n3vros** [comment]
same issue here

**Comment by SciresM** [comment]
This is just a corrupt emummc, not an atmosphere bug

**Comment by BaamAlex** [comment]
> This is just a corrupt emummc, not an atmosphere bug

What now? Mine or do you mean the OP?

**Comment by SciresM** [comment]
the issue tracker is for bugs, not for support. Seek support on discord.
