### ISSUE TITLE
Bitmap Screenshots

### ISSUE THREAD

**Issue by NO-ob** [Atmosphere-NX/Atmosphere#265]
## Feature Request
BMP or  PNG Screenshots
### Why would this feature be useful?
The screenshots on the switch look awful as they are very low quality jpegs 

[censored image]

**Comment by misson20000** [comment]
If someone figures it out and writes some docs on how to find relevant functions to patch I'll port it to other firmwares

**Comment by boringhexi** [comment]
Seconding the request for lossless screenshots. (I’m making this request because The Cutting Room Floor, a site for documenting unused video game content, does not allow lossy JPEG screenshots, not even high-quality ones.) Even some sort of raw format that needs to be converted to BMP or PNG later would be fine by me.

**Comment by SciresM** [comment]
Out of scope, for now.
