### ISSUE TITLE
Allow overriding the MAC address

### ISSUE THREAD

**Issue by kynax** [Atmosphere-NX/Atmosphere#824]
#### Overview:
Since connecting to Nintendo servers is not recommended when using a custom firmware, some of us put rules in our routers to block the connection.
However, when booting original firmware, the connection is still blocked.
It would be nice to be able to have a different MAC address when using Atmosphère so that the router rules that control the block could only apply when required.

### Why would this feature be useful?
It would encourage more people to be proactive with their network settings at home and still allow full use of network features in standard booting.

**Comment by SciresM** [comment]
Out of scope due to lack of research on how mac address is stored, where/how it's retrieved, etc.

If research is done demonstrating how to do this I'd be happy to consider it, in the meantime I'm sure it's possible for some researcher to write a .ips for the relevant sysmodule as a proof of concept?
