### ISSUE TITLE
Panic Error when i run hbmenu after starting a game or app

### ISSUE THREAD

**Issue by johner1** [Atmosphere-NX/Atmosphere#965]
**Error**
Panic Occurred while running Atmosphere.

Title ID: 010041544D530000
Error Desc: std::abort() (0xFFE)]

**Error report:**
[report_458f248d3.zip](https://github.com/Atmosphere-NX/Atmosphere/files/4679485/report_458f248d3.zip)

I updated my fw 9.1 to 10.0.2 & ams to 0.12 from 0.92 
Everything was working well but when i try to start hbmenu after opening any game/tinfoil. It gives that sudden error.

### Methods applied:
1. I did the fix bit with Hekate tools ----all good & gave same error.
2. I deleted sys-clk sys-con they gave new error so rerolled.
3. I use Fat32 yet i downgraded to 10.0.1 then again upped to 10.0.2 on fat32 then i moved my important Ntendo file to root.Started through hekate to primary fusee --found same error.
4. Tried the Ram issue--- deleted applet programs 1/1 to find fix which didn't change a thing.

**Fw & Ams**

10.0.2 & 0.12

What should i do ??

**Comment by fennectech** [comment]
I see this panic with 4 custom sysmodules   Seems to be memory related   (sys-con sys-ftpd-light sys-clk and tesla)

**Comment by johner1** [comment]
i checked out the issue with much more deliberation & found that it was problem with the ams package i replaced it with the latest one from git which was lastly from sdsetup. Btw,thanks.

**Comment by PrimetimeFluff** [comment]
I'm having the same issue. What did you do to fix it?
I've updated AMS from github.

**Comment by johner1** [comment]
just replaced with the ams from git...guess there were some diff files from sdsetup with those ams & sept folder.And this fixed the issue.Tried many methods you can check up.

**Comment by SciresM** [comment]
Not an atmosphere issue.

Sysmodules are exhausting the FS session limit (it appears most custom sysmodules outside atmosphere are not configuring themselves to only use one FS session instead of three, and are counting triple against the limit).

This is a fixed, unpatchable system limitation -- the developers of the sysmodules you use will need to release better behaved builds which correctly respect the limitations.

I'm reaching out to some sysmodule developers (e.g. https://github.com/exelix11/SysDVR/issues/58) to get them to do this where I can.
